# LVGL 9.4.0 scales LV_CHART_POINT_NONE (INT32_MAX) before checking it,
# overflowing signed arithmetic on empty/gapped line charts. Build a checked
# copy; leave the managed dependency and its integrity metadata untouched.
function(trimix_patch_lvgl_chart target source_root)
    get_filename_component(source_root "${source_root}" REALPATH)
    set(original "${source_root}/src/widgets/chart/lv_chart.c")
    file(SHA256 "${original}" digest)
    if(NOT digest STREQUAL "5ab1050c6981a037f915295f5f9a2f536a8679b2a78ae127f437dcf75bad1cd6")
        message(FATAL_ERROR "LVGL chart source changed; review the missing-point overflow patch")
    endif()
    file(READ "${original}" patched)
    foreach(index p_prev p_act)
        set(before "(int32_t)((int32_t)ser->y_points[${index}] - chart->ymin[ser->y_axis_sec]) * h")
        string(REPLACE "${before}"
            "ser->y_points[${index}] == LV_CHART_POINT_NONE ? 0 : ${before}"
            patched "${patched}")
    endforeach()
    set(output "${CMAKE_BINARY_DIR}/lvgl-chart-patched/lv_chart.c")
    file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/lvgl-chart-patched")
    file(WRITE "${output}.in" "${patched}")
    configure_file("${output}.in" "${output}" COPYONLY)
    get_target_property(sources ${target} SOURCES)
    set(retained)
    set(matches 0)
    foreach(source IN LISTS sources)
        get_filename_component(absolute "${source}" ABSOLUTE BASE_DIR "${source_root}")
        if(absolute STREQUAL original)
            math(EXPR matches "${matches} + 1")
        else()
            list(APPEND retained "${source}")
        endif()
    endforeach()
    if(NOT matches EQUAL 1)
        message(FATAL_ERROR "Expected one LVGL chart source in ${target}; found ${matches}")
    endif()
    list(APPEND retained "${output}")
    set_property(TARGET ${target} PROPERTY SOURCES "${retained}")
    target_include_directories(${target} PRIVATE "${source_root}/src/widgets/chart")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${original}")
endfunction()
