#!/usr/bin/env python3
"""Build LVGL alpha masks from the selected Tabler menu icons.

Requires librsvg (`rsvg-convert`) and ImageMagick (`magick`). The generated C
file is committed so firmware and simulator builds need neither tool.
"""

from pathlib import Path
import subprocess
import tempfile


ROOT = Path(__file__).resolve().parents[3]
SOURCE = ROOT / "software/firmware/assets/icons/tabler"
OUTPUT = ROOT / "software/firmware/main/ui/images/menu_icons.c"
ICONS = (
    ("flask", "menu_icon_analyse", 64),
    ("chart-line", "menu_icon_dive_planner", 64),
    ("history", "menu_icon_history", 64),
    ("scuba-diving-tank", "menu_icon_cylinders", 64),
    ("adjustments-horizontal", "menu_icon_settings", 64),
    ("scuba-diving-tank", "button_icon_cylinder", 24),
)


def run(*args: str) -> None:
    subprocess.run(args, check=True)


def c_array(name: str, data: bytes) -> str:
    lines = []
    for offset in range(0, len(data), 16):
        chunk = data[offset : offset + 16]
        lines.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    return (f"static const uint8_t {name}_map[] __attribute__((aligned(16))) = {{\n"
            + "\n".join(lines) + "\n};\n")


def descriptor(name: str, size: int) -> str:
    return f"""const lv_image_dsc_t {name} = {{
    .header = {{
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_A8,
        .w = {size},
        .h = {size},
        .stride = {size},
    }},
    .data_size = sizeof({name}_map),
    .data = {name}_map,
}};
"""


def main() -> None:
    output = """// Generated by scripts/generate_menu_icons.py from Tabler Icons SVGs.
// Do not edit this file by hand. Artwork is covered by assets/icons/tabler/LICENSE.
#include "menu_icons.h"

"""
    with tempfile.TemporaryDirectory(prefix="trimix-menu-icons-") as directory:
        temp = Path(directory)
        for filename, name, size in ICONS:
            png = temp / f"{name}.png"
            mask = temp / f"{name}.a8"
            run("rsvg-convert", "-w", str(size), "-h", str(size),
                str(SOURCE / f"{filename}.svg"), "-o", str(png))
            run("magick", str(png), "-alpha", "extract", "-depth", "8",
                f"gray:{mask}")
            data = mask.read_bytes()
            if len(data) != size * size:
                raise ValueError(f"Unexpected mask size for {filename}: {len(data)}")
            output += c_array(name, data) + "\n" + descriptor(name, size) + "\n"

    OUTPUT.write_text(output.rstrip() + "\n")
    print(f"Wrote {OUTPUT} ({sum(size * size for _, _, size in ICONS)} mask bytes)")


if __name__ == "__main__":
    main()
