#!/usr/bin/env python3
"""Build LVGL alpha masks and previews from the selected Ægir brand assets.

Requires ImageMagick (`magick`) and librsvg (`rsvg-convert`). The generated C
file is committed so normal firmware, simulator, and web builds need neither.
"""

from pathlib import Path
import subprocess
import tempfile


ROOT = Path(__file__).resolve().parents[3]
MARK = ROOT / "branding/aegir-mark.svg"
WORDMARK = ROOT / "branding/aegir-v1-wordmark.svg"
OUTPUT = ROOT / "software/firmware/main/ui/images/aegir_splash_images.c"
SPLASH_PREVIEW = ROOT / "branding/aegir-splash.png"
LOCKUP_PREVIEW = ROOT / "branding/aegir-lockup-dark.png"
MARK_WIDTH = 240
MARK_HEIGHT = 293
WORDMARK_WIDTH = 310


def run(*args: str) -> None:
    subprocess.run(args, check=True)


def c_array(name: str, data: bytes) -> str:
    lines = []
    for offset in range(0, len(data), 16):
        chunk = data[offset : offset + 16]
        lines.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    return f"static const uint8_t {name}[] = {{\n" + "\n".join(lines) + "\n};\n"


def descriptor(name: str, width: int, height: int) -> str:
    return f"""const lv_image_dsc_t {name} = {{
    .header = {{
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_A8,
        .w = {width},
        .h = {height},
        .stride = {width},
    }},
    .data_size = sizeof({name}_map),
    .data = {name}_map,
}};
"""


def main() -> None:
    with tempfile.TemporaryDirectory(prefix="aegir-splash-") as directory:
        temp = Path(directory)
        mark_png = temp / "mark.png"
        mark_mask = temp / "mark.a8"
        wordmark_png = temp / "wordmark.png"
        wordmark_mask = temp / "wordmark.a8"

        run("rsvg-convert", "-w", str(MARK_WIDTH), "-h", str(MARK_HEIGHT),
            str(MARK), "-o", str(mark_png))
        run("magick", str(mark_png), "-alpha", "extract", "-depth", "8",
            f"gray:{mark_mask}")
        run("rsvg-convert", "-w", str(WORDMARK_WIDTH), str(WORDMARK), "-o", str(wordmark_png))
        dimensions = subprocess.check_output(
            ["magick", "identify", "-format", "%w %h", str(wordmark_png)], text=True
        ).split()
        wordmark_width, wordmark_height = map(int, dimensions)
        if wordmark_width != WORDMARK_WIDTH:
            raise ValueError("Unexpected wordmark width")
        run("magick", str(wordmark_png), "-alpha", "extract", "-depth", "8", f"gray:{wordmark_mask}")

        mark_data = mark_mask.read_bytes()
        wordmark_data = wordmark_mask.read_bytes()
        if len(mark_data) != MARK_WIDTH * MARK_HEIGHT:
            raise ValueError("Unexpected mark mask size")
        if len(wordmark_data) != WORDMARK_WIDTH * wordmark_height:
            raise ValueError("Unexpected wordmark mask size")

        mark_mask_png = temp / "mark-mask.png"
        wordmark_mask_png = temp / "wordmark-mask.png"
        mark_white = temp / "mark-white.png"
        wordmark_white = temp / "wordmark-white.png"
        run("magick", "-size", f"{MARK_WIDTH}x{MARK_HEIGHT}", "-depth", "8",
            f"gray:{mark_mask}", str(mark_mask_png))
        run("magick", "-size", f"{WORDMARK_WIDTH}x{wordmark_height}", "-depth", "8",
            f"gray:{wordmark_mask}", str(wordmark_mask_png))
        run("magick", "-size", f"{MARK_WIDTH}x{MARK_HEIGHT}", "xc:white",
            str(mark_mask_png), "-compose", "CopyOpacity", "-composite", str(mark_white))
        run("magick", "-size", f"{WORDMARK_WIDTH}x{wordmark_height}", "xc:white",
            str(wordmark_mask_png), "-compose", "CopyOpacity", "-composite", str(wordmark_white))
        run("magick", "-size", "480x800", "canvas:#0B0F14",
            str(mark_white), "-geometry", "+120+166", "-composite",
            str(wordmark_white), "-geometry", "+85+493", "-composite",
            str(SPLASH_PREVIEW))

        wide_wordmark = temp / "wide-wordmark.png"
        wide_mask = temp / "wide-mask.png"
        wide_white = temp / "wide-white.png"
        run("rsvg-convert", "-w", "450", str(WORDMARK), "-o", str(wide_wordmark))
        wide_dimensions = subprocess.check_output(
            ["magick", "identify", "-format", "%w %h", str(wide_wordmark)], text=True
        ).split()
        wide_width, wide_height = map(int, wide_dimensions)
        run("magick", str(wide_wordmark), "-alpha", "extract", str(wide_mask))
        run("magick", "-size", f"{wide_width}x{wide_height}", "xc:white",
            str(wide_mask), "-compose", "CopyOpacity", "-composite", str(wide_white))
        run("magick", "-size", "960x360", "canvas:#0B0F14",
            str(mark_white), "-geometry", "+70+34", "-composite",
            str(wide_white), "-geometry", "+415+83", "-composite",
            str(LOCKUP_PREVIEW))

    output = """// Generated by scripts/generate_splash_assets.py from branding/aegir-mark.svg
// and branding/aegir-v1-wordmark.svg. Do not edit this file by hand.
#include "aegir_splash_images.h"

"""
    output += c_array("aegir_splash_mark_map", mark_data) + "\n"
    output += descriptor("aegir_splash_mark", MARK_WIDTH, MARK_HEIGHT) + "\n"
    output += c_array("aegir_splash_wordmark_map", wordmark_data) + "\n"
    output += descriptor("aegir_splash_wordmark", WORDMARK_WIDTH, wordmark_height)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(output)
    print(f"Wrote {OUTPUT} ({len(mark_data) + len(wordmark_data)} mask bytes)")


if __name__ == "__main__":
    main()
